---
- name: Télécharger un fichier avec Ansible
  hosts: zabbix
  vars:
    zabbix_db_password: "zabbix"
    mysql_root_password: "root"
  become: yes
  tasks:
    - name: Télécharger le fichier depuis une URL
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb"
        dest: "/test/zabbix-release_latest_7.2+debian12_all.deb"
    - name: Installer un fichier .deb
      apt:
        deb: "/test/zabbix-release_latest_7.2+debian12_all.deb"
    - name: update
      apt:
    - name: Installation des packets Zabbix
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
        update_cache: yes
      become: yes
    - name: Mise à jour du cache des paquets
      apt:
        update_cache: yes
      become: yes
    - name: Installation de MySQL
      apt:
        name:
          - mariadb-server
          - python3-mysqldb
        state: present
        update_cache: yes
      become: yes
    - name: Lancement service MYSQL
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes
    - name: Créer la base de données Zabbix
      mysql_db:
        name: zabbix
        state: present
        encoding: utf8mb4
        collation: utf8mb4_bin
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes
    - name: Créer l'utilisateur Zabbix
      mysql_user:
        name: zabbix
        host: localhost
        password: zabbix
        priv: "zabbix.*:ALL"
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes
    - name: Activer log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 1
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
      become: yes
    - name: Redémarrer et Activer les services Zabbix
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled:
      loop:
        - zabbix-server
        - zabbix-agent
    - name: Verifier si la BDD Zabbix est vide
      mysql_query: 
        login_db: zabbix
        query: SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'zabbix'
      register: db_check
    - name: Importer les schéma et les données zabbix
      shell: zcat /usr/share/zabbix/sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p{{ zabbix_db_password }} zabbix
      when: db_check.query_result[0][0] == 0
      args:
        executable: /bin/bash
    - name: Désactiver log_bin_trust_function_creators
      mysql_variables:
        variable: log_bin_trust_function_creators
        value: 0
        mode: global
        login_user: root
        login_password: "{{ mysql_root_password }}"
      become: yes
    - name: Configuration du mot de passe pour la basse de données du Serveur Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: "DBPassword={{ zabbix_db_password }}"
    - name: Redémarrage des services Zabbix
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
